//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDA.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoCliente
    {
        public GrupoCliente()
        {
            this.Cliente = new HashSet<Cliente>();
            this.PaqueteGrupoCliente = new HashSet<PaqueteGrupoCliente>();
            this.PromocionTipoCliente = new HashSet<PromocionTipoCliente>();
        }
    
        public long ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<long> UsuarioMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<PaqueteGrupoCliente> PaqueteGrupoCliente { get; set; }
        public virtual ICollection<PromocionTipoCliente> PromocionTipoCliente { get; set; }
    }
}
