//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDA.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TDAEntities : DbContext
    {
        public TDAEntities()
            : base("name=TDAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaseSalario> BaseSalario { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Color> Color { get; set; }
        public DbSet<Configuracion> Configuracion { get; set; }
        public DbSet<Dia> Dia { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<GrupoCliente> GrupoCliente { get; set; }
        public DbSet<Logs> Logs { get; set; }
        public DbSet<Marca> Marca { get; set; }
        public DbSet<Modelo> Modelo { get; set; }
        public DbSet<Movimiento> Movimiento { get; set; }
        public DbSet<Pagina> Pagina { get; set; }
        public DbSet<Pais> Pais { get; set; }
        public DbSet<Paquete> Paquete { get; set; }
        public DbSet<PaqueteDia> PaqueteDia { get; set; }
        public DbSet<PaqueteGrupoCliente> PaqueteGrupoCliente { get; set; }
        public DbSet<PaqueteProducto> PaqueteProducto { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Promocion> Promocion { get; set; }
        public DbSet<PromocionDia> PromocionDia { get; set; }
        public DbSet<PromocionPaquete> PromocionPaquete { get; set; }
        public DbSet<PromocionProducto> PromocionProducto { get; set; }
        public DbSet<PromocionTipoCliente> PromocionTipoCliente { get; set; }
        public DbSet<PromocionTipoProducto> PromocionTipoProducto { get; set; }
        public DbSet<Proveedor> Proveedor { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<RolPagina> RolPagina { get; set; }
        public DbSet<TipoIdentificacion> TipoIdentificacion { get; set; }
        public DbSet<TipoMovimiento> TipoMovimiento { get; set; }
        public DbSet<TipoProducto> TipoProducto { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Vehiculo> Vehiculo { get; set; }
        public DbSet<Venta> Venta { get; set; }
        public DbSet<VentaDetalle> VentaDetalle { get; set; }
        public DbSet<VentaDia> VentaDia { get; set; }
    }
}
