//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDA.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquete
    {
        public Paquete()
        {
            this.PaqueteDia = new HashSet<PaqueteDia>();
            this.PaqueteGrupoCliente = new HashSet<PaqueteGrupoCliente>();
            this.PaqueteProducto = new HashSet<PaqueteProducto>();
            this.PromocionPaquete = new HashSet<PromocionPaquete>();
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public long ID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<bool> ParaGrupoCliente { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<long> UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<long> UsuarioMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<PaqueteDia> PaqueteDia { get; set; }
        public virtual ICollection<PaqueteGrupoCliente> PaqueteGrupoCliente { get; set; }
        public virtual ICollection<PaqueteProducto> PaqueteProducto { get; set; }
        public virtual ICollection<PromocionPaquete> PromocionPaquete { get; set; }
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
