//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDA.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Movimiento = new HashSet<Movimiento>();
            this.PaqueteProducto = new HashSet<PaqueteProducto>();
            this.PromocionProducto = new HashSet<PromocionProducto>();
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public long ID { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Servicio { get; set; }
        public Nullable<bool> IVAExcencto { get; set; }
        public Nullable<long> TipoProducto { get; set; }
        public Nullable<long> Proveedor { get; set; }
        public Nullable<long> UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<long> UsuarioMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
    
        public virtual ICollection<Movimiento> Movimiento { get; set; }
        public virtual ICollection<PaqueteProducto> PaqueteProducto { get; set; }
        public virtual Proveedor Proveedor1 { get; set; }
        public virtual TipoProducto TipoProducto1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<PromocionProducto> PromocionProducto { get; set; }
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
