//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDA.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromocionTipoCliente
    {
        public long ID { get; set; }
        public Nullable<long> Promocion { get; set; }
        public Nullable<long> GrupoCliente { get; set; }
    
        public virtual GrupoCliente GrupoCliente1 { get; set; }
        public virtual Promocion Promocion1 { get; set; }
    }
}
