//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDA.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.RolPagina = new HashSet<RolPagina>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public long ID { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<RolPagina> RolPagina { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
