//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDA.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolPagina
    {
        public long ID { get; set; }
        public Nullable<long> Rol { get; set; }
        public Nullable<long> Pagina { get; set; }
    
        public virtual Pagina Pagina1 { get; set; }
        public virtual Rol Rol1 { get; set; }
    }
}
