//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDA.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public Vehiculo()
        {
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public long ID { get; set; }
        public string NoSerie { get; set; }
        public Nullable<long> Modelo { get; set; }
        public string Color { get; set; }
        public Nullable<int> Ano { get; set; }
        public string Resposable { get; set; }
        public string NumeroIdentificacion { get; set; }
        public Nullable<long> TipoIdentificacion { get; set; }
        public Nullable<long> UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<long> UsuarioMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
    
        public virtual Modelo Modelo1 { get; set; }
        public virtual TipoIdentificacion TipoIdentificacion1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
